// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SkillMastery is an object representing the database table.
type SkillMastery struct {
	UserID       string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	SkillTag     string    `boil:"skill_tag" json:"skill_tag" toml:"skill_tag" yaml:"skill_tag"`
	CurrentScore null.Int  `boil:"current_score" json:"current_score,omitempty" toml:"current_score" yaml:"current_score,omitempty"`
	LastUpdated  null.Time `boil:"last_updated" json:"last_updated,omitempty" toml:"last_updated" yaml:"last_updated,omitempty"`

	R *skillMasteryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L skillMasteryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SkillMasteryColumns = struct {
	UserID       string
	SkillTag     string
	CurrentScore string
	LastUpdated  string
}{
	UserID:       "user_id",
	SkillTag:     "skill_tag",
	CurrentScore: "current_score",
	LastUpdated:  "last_updated",
}

var SkillMasteryTableColumns = struct {
	UserID       string
	SkillTag     string
	CurrentScore string
	LastUpdated  string
}{
	UserID:       "skill_mastery.user_id",
	SkillTag:     "skill_mastery.skill_tag",
	CurrentScore: "skill_mastery.current_score",
	LastUpdated:  "skill_mastery.last_updated",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var SkillMasteryWhere = struct {
	UserID       whereHelperstring
	SkillTag     whereHelperstring
	CurrentScore whereHelpernull_Int
	LastUpdated  whereHelpernull_Time
}{
	UserID:       whereHelperstring{field: "\"skill_mastery\".\"user_id\""},
	SkillTag:     whereHelperstring{field: "\"skill_mastery\".\"skill_tag\""},
	CurrentScore: whereHelpernull_Int{field: "\"skill_mastery\".\"current_score\""},
	LastUpdated:  whereHelpernull_Time{field: "\"skill_mastery\".\"last_updated\""},
}

// SkillMasteryRels is where relationship names are stored.
var SkillMasteryRels = struct {
}{}

// skillMasteryR is where relationships are stored.
type skillMasteryR struct {
}

// NewStruct creates a new relationship struct
func (*skillMasteryR) NewStruct() *skillMasteryR {
	return &skillMasteryR{}
}

// skillMasteryL is where Load methods for each relationship are stored.
type skillMasteryL struct{}

var (
	skillMasteryAllColumns            = []string{"user_id", "skill_tag", "current_score", "last_updated"}
	skillMasteryColumnsWithoutDefault = []string{"user_id", "skill_tag"}
	skillMasteryColumnsWithDefault    = []string{"current_score", "last_updated"}
	skillMasteryPrimaryKeyColumns     = []string{"user_id", "skill_tag"}
	skillMasteryGeneratedColumns      = []string{}
)

type (
	// SkillMasterySlice is an alias for a slice of pointers to SkillMastery.
	// This should almost always be used instead of []SkillMastery.
	SkillMasterySlice []*SkillMastery
	// SkillMasteryHook is the signature for custom SkillMastery hook methods
	SkillMasteryHook func(context.Context, boil.ContextExecutor, *SkillMastery) error

	skillMasteryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	skillMasteryType                 = reflect.TypeOf(&SkillMastery{})
	skillMasteryMapping              = queries.MakeStructMapping(skillMasteryType)
	skillMasteryPrimaryKeyMapping, _ = queries.BindMapping(skillMasteryType, skillMasteryMapping, skillMasteryPrimaryKeyColumns)
	skillMasteryInsertCacheMut       sync.RWMutex
	skillMasteryInsertCache          = make(map[string]insertCache)
	skillMasteryUpdateCacheMut       sync.RWMutex
	skillMasteryUpdateCache          = make(map[string]updateCache)
	skillMasteryUpsertCacheMut       sync.RWMutex
	skillMasteryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var skillMasteryAfterSelectMu sync.Mutex
var skillMasteryAfterSelectHooks []SkillMasteryHook

var skillMasteryBeforeInsertMu sync.Mutex
var skillMasteryBeforeInsertHooks []SkillMasteryHook
var skillMasteryAfterInsertMu sync.Mutex
var skillMasteryAfterInsertHooks []SkillMasteryHook

var skillMasteryBeforeUpdateMu sync.Mutex
var skillMasteryBeforeUpdateHooks []SkillMasteryHook
var skillMasteryAfterUpdateMu sync.Mutex
var skillMasteryAfterUpdateHooks []SkillMasteryHook

var skillMasteryBeforeDeleteMu sync.Mutex
var skillMasteryBeforeDeleteHooks []SkillMasteryHook
var skillMasteryAfterDeleteMu sync.Mutex
var skillMasteryAfterDeleteHooks []SkillMasteryHook

var skillMasteryBeforeUpsertMu sync.Mutex
var skillMasteryBeforeUpsertHooks []SkillMasteryHook
var skillMasteryAfterUpsertMu sync.Mutex
var skillMasteryAfterUpsertHooks []SkillMasteryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SkillMastery) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SkillMastery) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SkillMastery) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SkillMastery) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SkillMastery) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SkillMastery) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SkillMastery) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SkillMastery) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SkillMastery) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillMasteryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSkillMasteryHook registers your hook function for all future operations.
func AddSkillMasteryHook(hookPoint boil.HookPoint, skillMasteryHook SkillMasteryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		skillMasteryAfterSelectMu.Lock()
		skillMasteryAfterSelectHooks = append(skillMasteryAfterSelectHooks, skillMasteryHook)
		skillMasteryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		skillMasteryBeforeInsertMu.Lock()
		skillMasteryBeforeInsertHooks = append(skillMasteryBeforeInsertHooks, skillMasteryHook)
		skillMasteryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		skillMasteryAfterInsertMu.Lock()
		skillMasteryAfterInsertHooks = append(skillMasteryAfterInsertHooks, skillMasteryHook)
		skillMasteryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		skillMasteryBeforeUpdateMu.Lock()
		skillMasteryBeforeUpdateHooks = append(skillMasteryBeforeUpdateHooks, skillMasteryHook)
		skillMasteryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		skillMasteryAfterUpdateMu.Lock()
		skillMasteryAfterUpdateHooks = append(skillMasteryAfterUpdateHooks, skillMasteryHook)
		skillMasteryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		skillMasteryBeforeDeleteMu.Lock()
		skillMasteryBeforeDeleteHooks = append(skillMasteryBeforeDeleteHooks, skillMasteryHook)
		skillMasteryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		skillMasteryAfterDeleteMu.Lock()
		skillMasteryAfterDeleteHooks = append(skillMasteryAfterDeleteHooks, skillMasteryHook)
		skillMasteryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		skillMasteryBeforeUpsertMu.Lock()
		skillMasteryBeforeUpsertHooks = append(skillMasteryBeforeUpsertHooks, skillMasteryHook)
		skillMasteryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		skillMasteryAfterUpsertMu.Lock()
		skillMasteryAfterUpsertHooks = append(skillMasteryAfterUpsertHooks, skillMasteryHook)
		skillMasteryAfterUpsertMu.Unlock()
	}
}

// One returns a single skillMastery record from the query.
func (q skillMasteryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SkillMastery, error) {
	o := &SkillMastery{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for skill_mastery")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SkillMastery records from the query.
func (q skillMasteryQuery) All(ctx context.Context, exec boil.ContextExecutor) (SkillMasterySlice, error) {
	var o []*SkillMastery

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to SkillMastery slice")
	}

	if len(skillMasteryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SkillMastery records in the query.
func (q skillMasteryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count skill_mastery rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q skillMasteryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if skill_mastery exists")
	}

	return count > 0, nil
}

// SkillMasteries retrieves all the records using an executor.
func SkillMasteries(mods ...qm.QueryMod) skillMasteryQuery {
	mods = append(mods, qm.From("\"skill_mastery\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"skill_mastery\".*"})
	}

	return skillMasteryQuery{q}
}

// FindSkillMastery retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSkillMastery(ctx context.Context, exec boil.ContextExecutor, userID string, skillTag string, selectCols ...string) (*SkillMastery, error) {
	skillMasteryObj := &SkillMastery{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"skill_mastery\" where \"user_id\"=$1 AND \"skill_tag\"=$2", sel,
	)

	q := queries.Raw(query, userID, skillTag)

	err := q.Bind(ctx, exec, skillMasteryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from skill_mastery")
	}

	if err = skillMasteryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return skillMasteryObj, err
	}

	return skillMasteryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SkillMastery) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no skill_mastery provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(skillMasteryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	skillMasteryInsertCacheMut.RLock()
	cache, cached := skillMasteryInsertCache[key]
	skillMasteryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			skillMasteryAllColumns,
			skillMasteryColumnsWithDefault,
			skillMasteryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(skillMasteryType, skillMasteryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(skillMasteryType, skillMasteryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"skill_mastery\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"skill_mastery\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into skill_mastery")
	}

	if !cached {
		skillMasteryInsertCacheMut.Lock()
		skillMasteryInsertCache[key] = cache
		skillMasteryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SkillMastery.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SkillMastery) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	skillMasteryUpdateCacheMut.RLock()
	cache, cached := skillMasteryUpdateCache[key]
	skillMasteryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			skillMasteryAllColumns,
			skillMasteryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update skill_mastery, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"skill_mastery\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, skillMasteryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(skillMasteryType, skillMasteryMapping, append(wl, skillMasteryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update skill_mastery row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for skill_mastery")
	}

	if !cached {
		skillMasteryUpdateCacheMut.Lock()
		skillMasteryUpdateCache[key] = cache
		skillMasteryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q skillMasteryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for skill_mastery")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for skill_mastery")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SkillMasterySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillMasteryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"skill_mastery\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, skillMasteryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in skillMastery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all skillMastery")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SkillMastery) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no skill_mastery provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(skillMasteryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	skillMasteryUpsertCacheMut.RLock()
	cache, cached := skillMasteryUpsertCache[key]
	skillMasteryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			skillMasteryAllColumns,
			skillMasteryColumnsWithDefault,
			skillMasteryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			skillMasteryAllColumns,
			skillMasteryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert skill_mastery, could not build update column list")
		}

		ret := strmangle.SetComplement(skillMasteryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(skillMasteryPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert skill_mastery, could not build conflict column list")
			}

			conflict = make([]string, len(skillMasteryPrimaryKeyColumns))
			copy(conflict, skillMasteryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"skill_mastery\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(skillMasteryType, skillMasteryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(skillMasteryType, skillMasteryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert skill_mastery")
	}

	if !cached {
		skillMasteryUpsertCacheMut.Lock()
		skillMasteryUpsertCache[key] = cache
		skillMasteryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SkillMastery record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SkillMastery) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no SkillMastery provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), skillMasteryPrimaryKeyMapping)
	sql := "DELETE FROM \"skill_mastery\" WHERE \"user_id\"=$1 AND \"skill_tag\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from skill_mastery")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for skill_mastery")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q skillMasteryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no skillMasteryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from skill_mastery")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for skill_mastery")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SkillMasterySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(skillMasteryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillMasteryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"skill_mastery\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, skillMasteryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from skillMastery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for skill_mastery")
	}

	if len(skillMasteryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SkillMastery) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSkillMastery(ctx, exec, o.UserID, o.SkillTag)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SkillMasterySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SkillMasterySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillMasteryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"skill_mastery\".* FROM \"skill_mastery\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, skillMasteryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in SkillMasterySlice")
	}

	*o = slice

	return nil
}

// SkillMasteryExists checks if the SkillMastery row exists.
func SkillMasteryExists(ctx context.Context, exec boil.ContextExecutor, userID string, skillTag string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"skill_mastery\" where \"user_id\"=$1 AND \"skill_tag\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, skillTag)
	}
	row := exec.QueryRowContext(ctx, sql, userID, skillTag)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if skill_mastery exists")
	}

	return exists, nil
}

// Exists checks if the SkillMastery row exists.
func (o *SkillMastery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SkillMasteryExists(ctx, exec, o.UserID, o.SkillTag)
}
